### ISSUE TITLE
bower warnings

### ISSUE THREAD

**Issue by Offirmo** [yahoo/intl-messageformat#103]
Hello,

on install, bower complains :
```
bower intl-messageformat#*  not-cached git://github.com/yahoo/intl-messageformat.git#*
bower intl-messageformat#*     resolve git://github.com/yahoo/intl-messageformat.git#*
bower intl-messageformat#*    download https://github.com/yahoo/intl-messageformat/archive/v1.1.0.tar.gz
bower intl-messageformat#*     extract archive.tar.gz
bower intl-messageformat#*     invalid-meta intl-messageformat is missing "main" entry in bower.json
bower intl-messageformat#*     invalid-meta intl-messageformat is missing "ignore" entry in bower.json
bower intl-messageformat#*         resolved git://github.com/yahoo/intl-messageformat.git#1.1.0
```

**Comment by ericf** [comment]
We never kept the bower install up to date, so we dropped it completely. We now recommend that you use npm.

**Comment by Offirmo** [comment]
Ok, thanks.

You may consider updating format.js doc which implies equals npm & bower support : http://formatjs.io/integrations/

**Comment by Offirmo** [comment]
And btw a bower plugin doesn't have to be kept "up to date" like a npm module. Publish it once, it then makes use of git tags to refer version.

So publishing intl modules on bower is a one-time action, which would only take a few minutes.
