### ISSUE TITLE
es5.js.map does not exist, but is reported within the source code

### ISSUE THREAD

**Issue by patrick-webs** [yahoo/intl-messageformat#105]
the package as downloaded from npm references a non-existent source map file. This causes an error in the chrome console whenever the browser developer tools are opened while the intl-messageformat library is included on the page.

```
$ npm install intl-messageformat
$ find . -iname "es5.js*"
./node_modules/intl-messageformat/lib/es5.js
./node_modules/intl-messageformat/src/es5.js
$  grep -F es5.js.map -R .
./node_modules/intl-messageformat/lib/es5.js://# sourceMappingURL=es5.js.map
```

I also noticed the same issue affects `intl-format-cache` and `intl-relativeformat` modules, presumably because they all use a similar build process.

I tried cloning this project and building it myself using Grunt and found that an es5.js.map file is generated at one point but is left in a temp directory and not included when the package for npm is created. I don't know if the solution is to include the map file in the npm package, or to remove the line beginning with `//#sourceMappingURL=`

```
$ pwd
~/src/intl-messageformat/ 
$ grunt
[. . .]
$ grep -F es5.js.map -R .
./lib/es5.js://# sourceMappingURL=es5.js.map
./tmp/src/es5.js://# sourceMappingURL=es5.js.map
$ find . -iname es5.js.map
./tmp/src/es5.js.map
```

**Comment by mattpage** [comment]
this happens to me too.

**Comment by jasonmit** [comment]
Fixed on master, will be in the next release.
