### ISSUE TITLE
React, ES6 Classes, Webpack

### ISSUE THREAD

**Issue by iammerrick** [yahoo/intl-messageformat#108]
From what I can tell this stack isn't currently supported in the React-Intl integrations as they leverage mixins. So I'm considering using this library directly. I would like to precompile the message format strings into the AST ahead of time which is why I was hoping for a webpack loader, though it appears this doesn't exist yet, should I build a webpack loader? Or am I just missing something?

Thanks!

**Comment by iammerrick** [comment]
I guess what's not clear to me is how to use this toolset, without using one of the integrations...

**Comment by caridy** [comment]
@iammerrick we are working on the next version of react-intl which is not going to use mixins. we have flushed the design this week, and @ericf is working on it as we speak. If that's the only reason why you are trying to use this pkg directly, I will recommend you to workaround the limitations for the time being, until we release the new version.

As for using this library directly, that's perfectly doable. I'm not sure I understand the issues you're facing, but the library works as standalone node pkg, which means you can bundle it up with browserify/webpack. As for the locale data needed, you have to require that explicit, e.g.: `require('intl-messageformat/dist/locale-data/aa.js')`, we have a provision to avoid bundling all locale data (https://github.com/yahoo/intl-messageformat/blob/master/package.json#L31-L34).

**Comment by iammerrick** [comment]
@caridy Thank you so much. I'll punt on this task till the next version comes out. :-) Thanks for the great response.

**Comment by iammerrick** [comment]
@caridy @ericf I know this is open source and so I don't have any expectations. I am grateful for your work. I am currently in a  position where I have to write my own abstraction for higher order components likely leveraging contexts orrrr wait for what you guys are working on. Do you have any timeline on it so I can better make this decision? Can I help implement the new design?

**Comment by caridy** [comment]
@ericf might give you a more realistic timeframe, but RC1 seems to be almost ready :).

**Comment by ericf** [comment]
@iammerrick I pushed the WIP React Intl [`v2-dev` branch](https://github.com/yahoo/react-intl/tree/v2-dev). And here's the list of [open issues that should be fixed by v2](https://github.com/yahoo/react-intl/labels/fixed-by-v2). Now that we have a stake in the ground that should address most of the open issues, I'm working on integrating the v2 branch into a few apps at Yahoo to work out any kinks with the new API and workflows.

**Comment by iammerrick** [comment]
@ericf How can I help you test it? Should I just point my package.json to that branch and start using the components?

**Comment by ericf** [comment]
@iammerrick I wouldn't recommend using the `v2-dev` branch in production. If you wanted to test it, you could clone the Git repo, checkout `v2-dev` and then link it locally via `npm link` and in your project: `npm link react-intl`. It's worth checking out the example apps, specifically: https://github.com/yahoo/react-intl/tree/v2-dev/examples/translations

**Comment by ChrisJamesC** [comment]
Any news about this?
