### ISSUE TITLE
How to convert AST object back into string pattern?

### ISSUE THREAD

**Issue by rightaway** [yahoo/intl-messageformat#118]
If you have an AST object representing an ICU message pattern, how can you convert that AST object to its string representation as a pattern?

I don't mean formatting the string. What I'd like to know is how to produce the pattern `'The price is: {price, number, USD}'` from an AST object rather than the formatted message `'The price is: $1.00'`.

**Comment by ericf** [comment]
You can write a printer; e.g., https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/print-icu-message.js

**Comment by rightaway** [comment]
Thank you!
