### ISSUE TITLE
print more details when message parsing fails

### ISSUE THREAD

**Issue by deddu** [yahoo/intl-messageformat#125]
Currently, when the message parsing fails, the following exception get thrown: `A message must be provided as a String or AST.`. [core.js L18](https://github.com/yahoo/intl-messageformat/blob/master/src/core.js#L18)

Sadly, this is also the resulting error when simple mistakes are made, such as missing keys. I am not sure if simply printing the message will do, but a more verbose error message would be nice to have. 
What are your thoughts on this?

**Comment by ericf** [comment]
The lines before it will throw when the message is parsed. Can you give an actual example where the details aren't provided and could be?

**Comment by deddu** [comment]
my most common case for this is when using the message format library trough dust.js - here's a typical error message with stacktrace:

```
[DUST:ERROR] Error in helper `formatMessage`: A message must be provided as a String or AST.
[DUST:ERROR] Rendering failed with error `TypeError: A message must be provided as a String or AST.`
[DUST:ERROR] Error in helper `formatMessage`: A message must be provided as a String or AST.
TypeError: A message must be provided as a String or AST.
    at new MessageFormat (/Users/web-home/node_modules/intl-messageformat/lib/core.js:21:15)
    at /Users/web-home/node_modules/dust-intl/node_modules/intl-format-cache/lib/memoizer.js:16:22
    at Object.formatMessage (/Users/web-home/node_modules/dust-intl/lib/helpers.js:237:21)
    at Chunk.helper (/Users/web-home/node_modules/dustjs-linkedin/lib/dust.js:811:33)
    at body_0 (evalmachine.<anonymous>:1:2965)
    at /Users/web-home/node_modules/adaro/lib/patch/index.js:89:33
    at /Users/web-home/node_modules/adaro/lib/reader/js.js:39:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
As you can see the stacktrace is not mentioning any file of my project. The reason for this is pretty simple though: is a simple key missing.  

Clearly this is happening because the message is `undefined`.  It is a meta issue, as it spans multiple libraries, what do you think?

**Comment by deddu** [comment]
Never mind this is an issue in dust-intl helpers. I will open there.
