### ISSUE TITLE
Missing sourcemaps

### ISSUE THREAD

**Issue by pawsong** [yahoo/intl-messageformat#126]
I am considering using react-intl. Thank you for your great job!

I found that webpack emits some warning messages because it cannot find sourcemap files.

For example, in `intl-messageformat/lib/en.js`, sourcemap `en.js.map` is referenced by source file:

``` javascript
// GENERATED FILE
"use strict";
exports["default"] = {"locale":"en","pluralRuleFunction":function (n,ord){var s=String(n).split("    ."),v0=!s[1],t0=Number(s[0])==n,n10=t0&&s[0].slice(-1),n100=t0&&s[0].slice(-2);if(ord)return n10=    =1&&n100!=11?"one":n10==2&&n100!=12?"two":n10==3&&n100!=13?"few":"other";return n==1&&v0?"one":"o    ther"}};

//# sourceMappingURL=en.js.map
```

But `en.js.map` file does not exist in the same directory (`intl-messageformat/lib`).

The same problem also occurs in related packages:
- intl-messageformat
- intl-relativeformat
- intl-format-cache
- intl-messageformat-parser

**Comment by ericf** [comment]
I'm fine with just stripping source maps. If you could open PRs to change the build to _not_ output source maps for the `lib/` files, I'll merge it in and release the packages.

**Comment by pawsong** [comment]
@ericf I was wondering it is ok or not, but instead of stripping source maps, I edited build scripts to emit source map files to lib directory and made pull requests on the above packages. Could you merge them?

**Comment by ericf** [comment]
Cool thanks! Yeah I can.

**Comment by christophehurpeau** [comment]
PR is https://github.com/yahoo/intl-messageformat/pull/131, @ericf do you plan to merge it ? I have the same issue with webpack warnings

**Comment by carl-berg** [comment]
Same issue here... any ETA on #131 or other fix?

**Comment by wazzzap** [comment]
Any updated on this?

**Comment by foobarfighter** [comment]
I'm getting these warnings too.  Any chance this is getting merged soon?

**Comment by jasonmit** [comment]
https://github.com/yahoo/intl-messageformat/pull/131 resolves this.  Will be in the next release.
