### ISSUE TITLE
Format datetime using pattern

### ISSUE THREAD

**Issue by guilhermesimoes** [yahoo/intl-messageformat#133]
I know we can do this:

```
"{updatedAt, date, long}"
```

And that we can do this:

```
formats = {
    time: {
        generalDate: {
            year: "numeric",
            month: "numeric",
            day: "numeric",
            hour: "numeric",
            minute: "numeric",
            second: "numeric"
        }
    }
};

"{updatedAt, time, generalDate}"
```

But is this there any way to format time with a pattern like `yyyy-MM-dd HH:mm:ss`, like in the [ICU user guide][1]?

I know this is more of a question than an issue, but I couldn't find the proper channel for this. Maybe consider adding a [CONTRIBUTING.md file][2]?

[1]: http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax
[2]: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by caridy** [comment]
@guilhermesimoes that's not how `Intl.DateTimeFormat` works in a browser. This library just relies on that, passing `generalDate` as the second argument in the `Intl.DateTimeFormat` constructor. You can try that in the browser's console:

```
new Intl.DateTimeFormat('pt', {
            year: "numeric",
            month: "numeric",
            day: "numeric",
            hour: "numeric",
            minute: "numeric",
            second: "numeric"
        }).format(Date.now())
"21/04/2016 13:59:31"
```

**Comment by guilhermesimoes** [comment]
> This library just relies on `Intl.DateTimeFormat`

Ah, gotcha. Anyway, thank you!
