### ISSUE TITLE
Value === 0 formatted as ''

### ISSUE THREAD

**Issue by santiagoaguiar** [yahoo/intl-messageformat#141]
The following code: 
```javascript
var IntlMessageFormat = require("intl-messageformat");
new IntlMessageFormat('{count}', 'en-us').format({count: 0});
```

Returns `''` instead of `'0'`. 

Is this the expected behavior since `count` was not formatted as number? 

It's caused by https://github.com/yahoo/intl-messageformat/blob/master/src/compiler.js#L158.

I wonder if this is by design, but to be honest, it was quite surprising. Using the normal string conversion rules seems more expected to me (excepting for `null`/`undefined` where defaulting to '' makes sense to me).

**Comment by jasonmit** [comment]
https://github.com/yahoo/intl-messageformat/issues/88
