### ISSUE TITLE
Formatting dynamic lists?

### ISSUE THREAD

**Issue by aaronbeall** [yahoo/intl-messageformat#148]
Is there a way to i18n the formatting of dynamic lists? 

For example, say I have a list of fruits `[apples, oranges, pears, grapes]` and I want to display it (in English) as `Apples, Oranges, Pears, and Grapes`. I have keys for each fruit, however the list itself is dynamically generated and may contain 2 fruits or 20 fruits (we can handle 0 or 1 fruit as a special case more easily so I'm not concerned about that). 

What is the best way to handle this?

**Comment by infojunkie** [comment]
Also interested in this feature. It would be great to implement Rails `to_sentence` function: https://apidock.com/rails/ActiveSupport/CoreExtensions/Array/Conversions/to_sentence which takes the current locale into consideration.

**Comment by caridy** [comment]
@aaronbeall we are working on standardizing that in javascript, it is currently at stage 2, more details here:
https://github.com/zbraniecki/proposal-intl-list-format

But this feature doesn't belong to the message format though, so I'm closing this one.

**Comment by aaronbeall** [comment]
@caridy Thanks for the info. So just so I understand, the list formatter would expect pre-formatted strings and format them as a list? We don't have to worry about the words being formatted differently, depending on position in the array?

And any idea when this might make it into FormatJS?

**Comment by caridy** [comment]
Correct. The low-level implementation that browsers will provide only add the right separators depending on the locale, nothing else. The rest is on the user. I don't know when FormatJS will land such features, I'm not actively working on that project anymore. Maybe @ericf or @juandopazo can comment.
