### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by WorldMaker** [yahoo/intl-messageformat#160]
I wrote a simple Typescript definition file for this library and would like to contribute it (and would be happy to help maintain it) if there is interest. The current philosophy for Typescript definitions is to try to provide them directly with the library itself on npm if/when possible, but I try to file it as an issue first before sending a PR just to make sure that the project is welcome to hosting its own Typescript definition. I know that not every project is comfortable with Typescript or wants to add Typescript files directly into their repository.

**Comment by jasonmit** [comment]
@WorldMaker send over a PR - happy to review.
