### ISSUE TITLE
How about ordinals?

### ISSUE THREAD

**Issue by carystanley** [yahoo/intl-messageformat#84]
It would be great if intl-messageformat supported ordinal numbers:

1st, 2nd, 3rd, 4th, 10th, 11th, 12th, 13th, 52nd, 53rd, etc...

Here is a really simple version of the logic:

```
    function ordinal_suffix(num) {
        var s = ["th", "st", "nd", "rd"],
            v = num % 100;
        return num + (s[(v - 20) % 10] || s[v] || s[0]);
    }
```

I am unsure if ordinal works differently in other languages besides english

**Comment by ericf** [comment]
I realized that we **do not** have that data to support `selectordinal` as I mentioned above. We could get this data from the [`make-plural.js` project](https://github.com/eemeli/make-plural.js) which would give us basic ordinal support without needing to implement RBNF.

**Comment by ericf** [comment]
@caridy what you wrote in https://github.com/yahoo/intl-messageformat/issues/84#issuecomment-64905934 is not actually correct — `select` argument types use exact matches. We currently have the cardinal pluralization rules, but we also need the ordinal ones, and with those we can support the `selectordinal` argument type [option #1](https://github.com/yahoo/intl-messageformat/issues/84#issuecomment-64826634).

**Comment by ericf** [comment]
## Update

I feel we should add basic ordinal support to this project by adding support for `selectordinal` arguments, [option #1 above](https://github.com/yahoo/intl-messageformat/issues/84#issuecomment-64826634). Here the tasks to implement this:

- [ ] Update [`grunt-extract-cldr-data`](https://github.com/yahoo/grunt-extract-cldr-data) to use [`make-plural`](https://github.com/eemeli/make-plural.js) which properly supports extracting ordinal pluralization rules from the CLDR.

- [ ] Update [`intl-messageformat-parser`](https://github.com/yahoo/intl-messageformat-parser) so it parsers `selectordinal` argument types and adds a new node type to its AST.

- [ ] Update this package to use the updated versions of `grunt-extract-cldr-data` and `intl-messageformat-parser`.

- [ ] Add new helper class to this package's message compiler which handles `selectordinal` argument types, and have it call the new pluralization functions created by `make-plural` with `true` as the second argument to the function, causing it to perform ordinal pluralization on the numeric value.

**Comment by ericf** [comment]
PR #102 Implements these `selectordinal` arguments, plus vast improvements to the locale data used by this package..

**Comment by piuccio** [comment]
@ericf  sorry to dig up this old issue again but the current `selectordinal` only works for numbers up to 20

```
{rank, selectordinal,
  one {#st} 
  two {#nd}
  few {#rd}
  other {#th}
}
```

with `{rank: 21}` generates `21th` which should instead be `21st`. Same goes for all numbers ending with `1`, `2`, `3` bigger than `20`.

I'm not sure if you want to track this problem somehow.

**Comment by MartinDawson** [comment]
@piuccio I tried numbers going up to 40. All work as expected.

Are you using latest `react-intl`?

Here's my code so you can try and see different:

```
export const floorMessages = (positionLowestFloor, positionHighestFloor) => {
  const ordinals = 'selectordinal, one {#st} two {#nd} few {#rd} other {#th}';

  return defineMessages({
    singleFloor: { id: 'Floor.singleFloor', defaultMessage: `{positionLowestFloor, ${ordinals} } floor`, values: { positionLowestFloor } },
    multiFloor: { id: 'Floor.multiFloor', defaultMessage: `{positionLowestFloor, ${ordinals}} to {positionHighestFloor, ${ordinals}} floor`, values: { positionLowestFloor, positionHighestFloor } },
  });
};
```

**Comment by piuccio** [comment]
You're right, I messed up my translation files
