### ISSUE TITLE
Internet Explorer 8 and Browserify

### ISSUE THREAD

**Issue by jerrysu** [yahoo/intl-messageformat#90]
Simply using `require('intl-messageformat');` in a bundle that is browserified results in JavaScript errors in IE8. The errors occur as a result of the keyword `default` being used as a property for the modules that use esnext.

I'm probably going to workaround this by including `IntlMessageFormat` on `window` through the bower package, but I haven't quite figured this out with `intl-format-cache`.

I'm curious if this is a known issue or if there is some way to bundle this package with browserify and have it work in IE8.

**Comment by ericf** [comment]
Good catch! We don't have automated tests for Browserify, otherwise this would have been caught. I'll update all of the packages' `index.js` files that are used by browserify to work with an ES3 environment.
