### ISSUE TITLE
Version number in bower.json is wrong

### ISSUE THREAD

**Issue by csnover** [yahoo/intl-messageformat#95]
n/t

**Comment by ericf** [comment]
https://github.com/yahoo/intl-messageformat/pull/96#issuecomment-73556971

**Comment by csnover** [comment]
Er, I’m using bower.

**Comment by ericf** [comment]
@csnover the decision to remove the `bower.json` file is bring this inline with the reality of how we've been managing this project — which is that we haven't been keeping the file up to date.
